basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('customer/register/',views.customer.register,name="cust_register"),
    path('vendor/register',views.vendor.register,name="vendor_register"),
    path('customer/login',views.customer.user_login,name='cust_login'),
    path('vendor/login',views.vendor.user_login,name='vendor_login'),
    path('vendor_home/',views.VendorHome,name='vendor_home'),
    path('customer_home',views.CustomerHome,name='customer_home'),
    path('add_item',views.Additems,name='add_item'),
    path('DeleteItem',views.deleteitems,name='DeleteItem'),
    path('EditItem',views.edititems,name='EditItem'),
    path('EditItemSubmit',views.edititems_submit,name='EditItemSubmit'),
    path('ChangeAddress',views.ChangeAddress,name='ChangeAddress'),
    path('AddBalance',views.AddBalance,name='AddBalance'),
    path('AddItemToCart',views.AddItemToCart,name='AddItemToCart'),
    path('AddItemToWishList',views.AddItemToWishList,name='AddItemToWishList'),
    path('Cart',views.cart,name='Cart'),
    path('WishList',views.wishlist,name='WishList'),
    path('DeleteItemFromWishList',views.DeleteItemFromWishList,name='DeleteItemFromWishList'),
    path('DeleteItemFromCart',views.DeleteItemFromCart,name='DeleteItemFromCart'),
    path('BuyItem',views.BuyItem,name='BuyItem'),
    path('CustomerOrderHistory',views.CustomerOrderHistory,name='CustomerOrderHistory'),
    path('CompletedOrder',views.CompleteOrder,name='CompletedOrder'),
    path('ViewOrders',views.ViewOrders,name='ViewOrders'),
    path('FindUser',views.FindUser,name='FindUser'),
    path('GoogleHome',views.GoogleHome,name='GoogleHome'),
    path('google_vendor',views.googlevendor,name='google_vendor'),
    path('google_customer',views.googlecustomer,name='google_customer'),
    path('export/xls/', views.GenerateReport, name='export_orders'),
]

e_commerce/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import *

urlpatterns = [
    path('basic_app/',include('basic_app.urls')),
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path('logout/',views.user_logout,name='logout'),
    path('', include('social_django.urls', namespace='social')),
    path('account/',include('allauth.urls'))
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
# Create your models here.


class CustProfileInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    Name = models.CharField(max_length=240,unique=False,default=None)
    Phone = models.IntegerField(validators=[MinValueValidator(1000000000),
                                       MaxValueValidator(9999999999)],unique=True,default=None)
    Address=models.CharField(max_length=240,unique=False,default=None)
    Zipcode=models.IntegerField(validators=[MinValueValidator(100000),
                                       MaxValueValidator(999999)],unique=False,default=None)
    wallet_balance=models.BigIntegerField(default=0)


    def __str__(self):
        return self.user.username

class VendorProfileInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    #additional
    Name = models.CharField(max_length=240,unique=False,default=None)
    Phone = models.IntegerField(validators=[MinValueValidator(1000000000),
                                       MaxValueValidator(9999999999)],unique=True,default=None)
    Address=models.CharField(max_length=240,unique=False,default=None)
    Shop_Name = models.CharField(max_length=240,unique=False,default=None)
    order_history=models.FileField(upload_to='order_file/',default=None)

    def __str__(self):
        return self.user.username

class SoldItem(models.Model):
    vendor=models.ForeignKey(VendorProfileInfo, on_delete=models.CASCADE)
    name=models.CharField(max_length=100)
    picture=models.ImageField(upload_to='item_photo',blank=True)
    description=models.TextField(max_length=256)
    price=models.IntegerField(default=0)
    available_quantity=models.IntegerField(default=0)
    sold_quantity=models.IntegerField(default=0)

class PurchasedItem(models.Model):
    customer=models.ForeignKey(CustProfileInfo, on_delete=models.CASCADE)
    item=models.ForeignKey(SoldItem, on_delete=models.CASCADE)
    quantity=models.IntegerField(default=0)
    order_complete=models.BooleanField(default=False)
    cost=models.BigIntegerField(default=0)

class CartItem(models.Model):
    customer=models.ForeignKey(CustProfileInfo, on_delete=models.CASCADE)
    item=models.ForeignKey(SoldItem, on_delete=models.CASCADE)
    requested_quantity=models.IntegerField(default=0)
    cost=models.BigIntegerField(default=0)

class WishList(models.Model):
    customer=models.ForeignKey(CustProfileInfo, on_delete=models.CASCADE)
    item=models.ForeignKey(SoldItem, on_delete=models.CASCADE)

basic_app/forms.py
from django import forms
from basic_app.models import CustProfileInfo,VendorProfileInfo,SoldItem
from django.contrib.auth.models import User

class customer_profile:
    class UserForm(forms.ModelForm):
        password=forms.CharField(widget=forms.PasswordInput())
        confirm_password=forms.CharField(widget=forms.PasswordInput())
        class Meta():
            model = User
            fields=('username','email','password','confirm_password')

    class UserProfileInfoForm(forms.ModelForm):
        class Meta():
            model = CustProfileInfo
            fields=('Name','Phone','Address','Zipcode')

class vendor_profile:
    class UserForm(forms.ModelForm):
        password=forms.CharField(widget=forms.PasswordInput())
        confirm_password=forms.CharField(widget=forms.PasswordInput())
        class Meta():
            model = User
            fields=('username','email','password','confirm_password')
    class UserProfileInfoForm(forms.ModelForm):
        class Meta():
            model = VendorProfileInfo
            fields=('Name','Phone','Address','Shop_Name')

class item_form(forms.ModelForm):
    class Meta():
        model = SoldItem
        fields = ('name','picture','description','price','available_quantity')

basic_app/views.py
from django.shortcuts import render,redirect
from basic_app.models import CustProfileInfo,VendorProfileInfo,SoldItem,PurchasedItem,CartItem,WishList
from django.contrib.auth.models import User
from basic_app.forms import customer_profile,vendor_profile,item_form
from django.contrib import messages
# Create your views here.
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings
import xlwt
from xlwt import Workbook
from django.core.files.storage import FileSystemStorage
import xlrd

host_user=settings.DEFAULT_FROM_EMAIL

def index(request):
    return render(request,'basic_app/home.html')



class customer():
    def register(request):
        registered=False

        if request.method=='POST':
            cust_user_form=customer_profile.UserForm(request.POST)
            cust_profile_form = customer_profile.UserProfileInfoForm(request.POST)
            username=request.POST.get('username')
            email=request.POST.get('email')
            password1=request.POST['password']
            password2=request.POST['confirm_password']
            if password1==password2:
                if cust_user_form.is_valid() and cust_profile_form.is_valid():
                    user = cust_user_form.save(commit=False)
                    user.save()
                    user.set_password(user.password)
                    user.first_name="customer"
                    user.save()
                    profile=cust_profile_form.save(commit=False)
                    profile.user = user
                    profile.save()

                    registered=True
                    user=authenticate(username=username,password=password1)
                    login(request,user)
                    return redirect('/basic_app/customer_home')
                else:
                    return HttpResponse(cust_user_form.errors,cust_profile_form.errors)
            else:
                return HttpResponse("'<script>alert(\'Passwords do not match\');</script>'")
        else:
            cust_user_form=customer_profile.UserForm()
            cust_profile_form = customer_profile.UserProfileInfoForm()
        return render(request,'basic_app/custregister.html',{'cust_user_form':cust_user_form,'cust_profile_form':cust_profile_form,
        'registered':registered})

    def user_login(request):
        if request.method=='POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username,password=password)
            try:
                profile=User.objects.get(username=username,first_name="customer")
            except:
                return HttpResponse("'<script>alert(\'You are not a Customer\');</script>'")
            if user:
                if user.is_active:
                    login(request,user)
                    return redirect('/basic_app/customer_home')
                else:
                    return HttpResponse("'<script>alert(\'Account not active\');</script>'")
            else:
                return HttpResponse('<script>alert(\'Invalid login details\');</script>')
        else:
            return render(request,'basic_app/home.html',{})


class vendor():


    def register(request):
        registered=False

        if request.method=='POST':
            vendor_user_form=vendor_profile.UserForm(request.POST)
            vendor_profile_form = vendor_profile.UserProfileInfoForm(request.POST)

            username=request.POST.get('username')
            email=request.POST.get('email')
            password1=request.POST.get('password')
            password2=request.POST.get('confirm_password')
            if password1==password2:
                if vendor_user_form.is_valid() and vendor_profile_form.is_valid():
                    user = vendor_user_form.save()
                    user.save()
                    user.set_password(user.password)
                    user.first_name="vendor"
                    user.save()
                    profile=vendor_profile_form.save(commit=False)
                    profile.user = user
                    profile.save()
                    registered=True
                    user=authenticate(username=username,password=password1)
                    login(request,user)
                    return redirect('/basic_app/vendor_home')
                else:
                    return HttpResponse(vendor_user_form.errors,vendor_profile_form.errors)
            else:
                return HttpResponse('<script>alert(\'Passwords do not match\');</script>')
        else:
            vendor_user_form=vendor_profile.UserForm()
            vendor_profile_form = vendor_profile.UserProfileInfoForm()
        return render(request,'basic_app/vendorregister.html',{'vendor_user_form':vendor_user_form,'vendor_profile_form':vendor_profile_form,
        'registered':registered})

    def user_login(request):
        if request.method=='POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(username=username,password=password)
            try:
                profile=User.objects.get(username=username,first_name="vendor")
            except:
                return HttpResponse("'<script>alert(\'You are not a Vendor\');</script>'")
            if user:
                if user.is_active:
                    login(request,user)
                    return redirect('/basic_app/vendor_home')
                else:
                    return HttpResponse("'<script>alert(\'Account not active\');</script>'")
            else:
                return HttpResponse('<script>alert(\'Invalid login details\');</script>')
        else:
            return render(request,'basic_app/home.html',{})

@login_required
def user_logout(request):
    return HttpResponseRedirect(reverse('index'))

def VendorHome(request):
    current_user=request.user
    user=User.objects.get(first_name='vendor',username=current_user.username)
    vendor=VendorProfileInfo.objects.get(user_id=user.id)
    items=SoldItem.objects.filter(vendor=vendor).order_by('id')

    if vendor is None:
        return render(request, 'basic_app/home.html',{"message":"Login again"})

    return render(request, 'basic_app/vendor_home.html', {'user':user,'vendor':vendor, 'items':items})

def CustomerHome(request):
    current_user=request.user
    user=User.objects.get(first_name='customer',username=current_user.username)
    customer=CustProfileInfo.objects.get(user_id=user.id)
    items=SoldItem.objects.all().order_by('-sold_quantity')

    if customer is None:
        return render(request, 'basic_app/home.html',{"message":"Login again"})

    return render(request, 'basic_app/cust_home.html', {'user':user,'customer':customer, 'items':items,})

def Additems(request):
    current_user=request.user
    user=User.objects.get(first_name='vendor',username=current_user.username)
    vendor=VendorProfileInfo.objects.get(user_id=user.id)
    if request.method == 'POST':
        items=item_form(request.POST,request.FILES)
        if items.is_valid():
            form=items.save(commit=False)
            form.vendor=vendor
            form.save()
            return redirect('/basic_app/add_item')
        else:
            return HttpResponse(items.errors)
    else:
        form=item_form()
    return render(request,'basic_app/additem.html',{'user':user,'vendor':vendor,'form':form})

def deleteitems(request):
    current_user=request.user
    user=User.objects.get(first_name='vendor',username=current_user.username)
    vendor=VendorProfileInfo.objects.get(user_id=user.id)
    itemid=request.POST['item_id']
    item=SoldItem.objects.get(id=itemid)
    if vendor.id==item.vendor_id:
        item.delete()
    return redirect('/basic_app/vendor_home')

def edititems(request):
    current_user=request.user
    user=User.objects.get(first_name='vendor',username=current_user.username)
    vendor=VendorProfileInfo.objects.get(user_id=user.id)
    itemid=request.POST['item_id']
    item=SoldItem.objects.get(id=itemid)
    return render(request,'basic_app/edititem.html',{'user':user,'vendor':vendor,'item':item})

def edititems_submit(request):
    current_user=request.user
    user=User.objects.get(first_name='vendor',username=current_user.username)
    vendor=VendorProfileInfo.objects.get(user_id=user.id)
    itemid=request.POST['item_id']
    prev_item=SoldItem.objects.get(id=itemid)
    if request.FILES.get('picture'):
        item=SoldItem(id=itemid, name=request.POST['name'], picture=request.FILES['picture'], price=request.POST['price'], description=request.POST['description'], available_quantity=request.POST['available_quantity'],vendor_id=vendor.id)
        item.save()
    else:
        item=SoldItem(id=itemid, name=request.POST['name'], picture= prev_item.picture, price=request.POST['price'], description=request.POST['description'], available_quantity=request.POST['available_quantity'],vendor_id=vendor.id)
        item.save()
    return redirect('/basic_app/vendor_home')


def ChangeAddress(request):
    current_user=request.user
    user=User.objects.get(first_name='customer',username=current_user.username)
    customer=CustProfileInfo.objects.get(user_id=user.id)
    if request.method=='POST':
        address=request.POST['address']
        customer.Address=address
        customer.save()
        return redirect('/basic_app/customer_home')
    else:
        return render(request,'basic_app/changeaddress.html',{'user':user,'customer':customer})

def AddBalance(request):
    current_user=request.user
    user=User.objects.get(first_name='customer',username=current_user.username)
    customer=CustProfileInfo.objects.get(user_id=user.id)
    if request.method=='POST':

templates/basic_app/CustOrderHistory.html
{% extends "basic_app/homepage.html" %}
{% block dropdown_content %}
<ul class="list-group">
<li class="list-group-item"><a href="#">Username: {{user.username}}<br></a></li>
<li class="list-group-item"><a href="#">Address:  {{customer.Address}}<br></a></li>
<li class="list-group-item"><a href="#">Wallet Balance: {{customer.wallet_balance}}<br></a></li>
<li class="list-group-item"><a href="{% url 'basic_app:customer_home'%}">Home</a></li>
<li class="list-group-item"><a href="{% url 'basic_app:ChangeAddress'%}">Change Address</a></li>
<li class="list-group-item"><a href="{% url 'basic_app:AddBalance'%}">Add Money to Wallat</a></li>
<li class="list-group-item"><a href="{% url 'basic_app:Cart'%}">Cart</a></li>
<li class="list-group-item"><a href="{% url 'basic_app:WishList'%}">Wish list</a></li>
<li class="list-group-item"><a href="{% url 'basic_app:CustomerOrderHistory'%}">Order history</a></li>
</ul>

{% endblock %}

{% block base_body %}
{% load my_extras %}
<div style="width:100%;justify-content:center;text-align:center;font-family: 'Dosis', sans-serif;color:red;font-size:20px;" class="container">
  {{message}}
</div>
<div style="width:100%;justify-content:center;text-align:center;" class="container">
  <h1 style="font-family: 'Dosis', sans-serif;">Cart</h1>
</div>
{% for item in items %}
<div id="custshowitem" style="height:34vh;" class="container">
  <div class="row">
    <div id="itempiccol" class="col">
      {% if item.item.picture %}
      <img src="{{item.item.picture.url}}" alt="picture" width="10%" height="10%">
      {% endif %}
      <br>
    </div>
    <div id="itemcol" class="col">
      {{item.item.name}}
      <br>
      Vendor : {{item.item.vendor.user.username}}
      <br>
      Description : {{item.item.description}}
      <br>
      Price : {{item.item.price}}
      <br>
      Quantity : {{item.quantity}}
      <br>
      Total Cost : {{item.cost}}
    </div>
    <div id="itembtn" class="col">
      {% if item.order_complete %}
        <div style="width:100%;justify-content:center;text-align:center;" class="container">
          <h1 style="font-family: 'Dosis', sans-serif;color:green;">Order completed</h1>
        </div>
      {% else %}
        <form action="/basic_app/CompletedOrder" method="POST">
          {% csrf_token %}
          <button style="margin-left:140px;"  class="btn btn-success" type="submit" value="{{item.id}}" name="CompOrdbtn">Order Received</button>
        </form>
      {% endif %}
    </div>
  </div>
</div>
{% endfor %}
{% endblock %}

templates/basic_app/GoogleHome.html
{% extends "basic_app/base.html" %}
{% block base_body %}
{% if user.is_authenticated %}
<div class="col box1">
<h1>Select</h1>
<a id="googlecust" href="{% url 'basic_app:google_customer'%}">Customer</a>
<a id="googlevendor" href="{% url 'basic_app:google_vendor'%}">Vendor</a>
</div>
{% else %}

You are not Logged in

{% endif %}

{% endblock %}

templates/basic_app/cart.html
{% extends "basic_app/homepage.html" %}
{% block dropdown_content %}
<ul class="list-group">
<li class="list-group-item"><a href="#">Username: {{user.username}}<br></a></li>
<li class="list-group-item"><a href="#">Address:  {{customer.Address}}<br></a></li>
<li class="list-group-item"><a href="#">Wallet Balance: {{customer.wallet_balance}}<br></a></li>
<li class="list-group-item"><a href="{% url 'basic_app:customer_home'%}">Home</a></li>
<li class="list-group-item"><a href="{% url 'basic_app:ChangeAddress'%}">Change Address</a></li>
<li class="list-group-item"><a href="{% url 'basic_app:AddBalance'%}">Add Money to Wallat</a></li>
<li class="list-group-item"><a href="{% url 'basic_app:Cart'%}">Cart</a></li>
<li class="list-group-item"><a href="{% url 'basic_app:WishList'%}">Wish list</a></li>
<li class="list-group-item"><a href="{% url 'basic_app:CustomerOrderHistory'%}">Order history</a></li>
</ul>

{% endblock %}

{% block base_body %}
{% load my_extras %}
<div style="width:100%;justify-content:center;text-align:center;font-family: 'Dosis', sans-serif;color:red;font-size:20px;" class="container">
  {{message}}
</div>
<div style="width:100%;justify-content:center;text-align:center;" class="container">
  <h1 style="font-family: 'Dosis', sans-serif;">Cart</h1>
</div>
{% for item in items %}
<div id="custshowitem" style="height:34vh;" class="container">
  <div class="row">
    <div id="itempiccol" class="col">
      {% if item.item.picture %}
      <img src="{{item.item.picture.url}}" alt="picture" width="10%" height="10%">
      {% endif %}
      <br>
    </div>
    <div id="itemcol" class="col">
      {{item.item.name}}
      <br>
      Vendor : {{item.item.vendor.user.username}}
      <br>
      Description : {{item.item.description}}
      <br>
      Price : {{item.item.price}}
      <br>
      Available Quantity : {{item.item.available_quantity}}
      <br>
      Required Quantity : {{item.requested_quantity}}
      <br>
      Total Cost : {{item.cost}}
    </div>
    <div id="itembtn" class="col">
      <form action="/basic_app/BuyItem" method="POST">
          {% csrf_token %}
          <button style="margin-left:140px;"  class="btn btn-dark" type="submit" value="{{item.id}}" name="Buybtn">Buy Item</button>
      </form>
      <form action="/basic_app/DeleteItemFromCart" method="POST">
          {% csrf_token %}
          <button style="margin-left:140px;"  class="btn btn-dark" type="submit" value="{{item.id}}" name="removebtn">Remove</button>
      </form>
    </div>

  </div>
</div>
{% endfor %}
{% endblock %}

templates/basic_app/changeaddress.html
{% extends "basic_app/homepage.html" %}
{% block dropdown_content %}
<ul class="list-group">
<li class="list-group-item"><a href="#">Username: {{user.username}}<br></a></li>
<li class="list-group-item"><a href="#">Address:  {{customer.Address}}<br></a></li>
<li class="list-group-item"><a href="#">Wallet Balance: {{customer.wallet_balance}}<br></a></li>
<li class="list-group-item"><a href="{% url 'basic_app:customer_home'%}">Home</a></li>
<li class="list-group-item"><a href="{% url 'basic_app:ChangeAddress'%">Change Address</a></li>
<li class="list-group-item"><a href="{% url 'basic_app:AddBalance'%}">Add Money to Wallat</a></li>
<li class="list-group-item"><a href="{% url 'basic_app:Cart'%}">Cart</a></li>
<li class="list-group-item"><a href="{% url 'basic_app:WishList'%}">Wish list</a></li>
<li class="list-group-item"><a href="{% url 'basic_app:CustomerOrderHistory'%}">Order history</a></li>
</ul>

{% endblock %}

{% block base_body %}
<div id="custbox" class="container-fluid">
  <h2>Type new address</h2>
  <form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    <p><label for="address">Address:</label><input type="text" name="address" maxlength="150" value="{{customer.Address}}" required="" id="address">
    </p>
    <input type="submit" class="btn btn-dark" name="" value="Change Address">
  </form>
</div>
{% endblock %}

templates/basic_app/cust_home.html
{% extends "basic_app/homepage.html" %}
{% block dropdown_content %}
<ul class="list-group">
<li class="list-group-item"><a href="#">Username: {{user.username}}<br></a></li>
<li class="list-group-item"><a href="#">Address:  {{customer.Address}}<br></a></li>
<li class="list-group-item"><a href="#">Wallet Balance: {{customer.wallet_balance}}<br></a></li>
<li class="list-group-item"><a href="{% url 'basic_app:customer_home'%}">Home</a></li>
<li class="list-group-item"><a href="{% url 'basic_app:ChangeAddress'%}">Change Address</a></li>
<li class="list-group-item"><a href="{% url 'basic_app:AddBalance'%}">Add Money to Wallat</a></li>
<li class="list-group-item"><a href="{% url 'basic_app:Cart'%}">Cart</a></li>
<li class="list-group-item"><a href="{% url 'basic_app:WishList'%}">Wish list</a></li>
<li class="list-group-item"><a href="{% url 'basic_app:CustomerOrderHistory'%}">Order history</a></li>
</ul>

{% endblock %}

{% block base_body %}
{% load my_extras %}
<div style="width:100%;justify-content:center;text-align:center;font-family: 'Dosis', sans-serif;color:red;font-size:20px;" class="container">
  {{message}}
</div>

{% for item in items %}

<div id="custshowitem" class="container">
  <div class="row">
    <div id="itempiccol" class="col">
      {% if item.picture %}
      <img src="{{item.picture.url}}" alt="picture" width="10%" height="10%">
      {% endif %}
      <br>
    </div>
    <div id="itemcol" class="col">
      {{item.name}}
      <br>
      Vendor : {{item.vendor.user.username}}
      <br>
      Description : {{item.description}}
      <br>
      Price : {{item.price}}
      <br>
      Available Quantity : {{item.available_quantity}}
    </div>
    <div id="itembtn" class="col">
      <form action="/basic_app/AddItemToCart" method="POST">
          {% csrf_token %}
          Quantity : <input type="number" name="quantity" min="1" max="{{item.available_quantity}}" required>
          <button class="btn btn-dark" type="submit" value="{{item.id}}" name="Cartbtn">Add to Cart</button>

      </form>
      <form action="/basic_app/AddItemToWishList" method="POST">
          {% csrf_token %}
          <button style="margin-left:149px;"  class="btn btn-dark" type="submit" value="{{item.id}}" name="wishlistbtn">Add to Wish list</button>
      </form>
    </div>

  </div>
</div>

{% endfor %}
{% endblock %}

templates/basic_app/edititem.html
{% extends "basic_app/homepage.html" %}
{% block dropdown_content %}
<ul class="list-group">
  <li class="list-group-item"><a href="#">Username: {{user.username}}<br></a></li>
  <li class="list-group-item"><a href="#">Address:  {{vendor.Address}}<br></a></li>
  <li class="list-group-item"><a href="#">Shop Name: {{vendor.Shop_Name}}<br></a></li>
  <li class="list-group-item"><a href="{% url 'basic_app:vendor_home'%}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'basic_app:add_item'%}">Add items</a></li>
  <li class="list-group-item"><a href="{% url 'basic_app:ViewOrders'%}">View orders</a></li>
</ul>
{% endblock %}

{% block base_body %}
<div id="custbox" class="container-fluid">
  <h2>Item Form</h2>
  <form enctype="multipart/form-data" action="/basic_app/EditItemSubmit" method="POST">
    {% csrf_token %}
    <p><label for="id_name">Name:</label> <input type="text" value="{{item.name}}" name="name" maxlength="100" required="" id="id_name"></p>
    <p><label for="id_picture">Picture:</label> <input type="file" name="picture" accept="image/*" id="id_picture">Leave blank if not want to change.</p>
    <p><label for="id_description">Description:</label> <textarea name="description" value="{{item.description}}" cols="40" rows="10" maxlength="256" required="" id="id_description"></textarea></p>
    <p><label for="id_price">Price:</label> <input type="number" name="price" value="{{item.price}}" required="" id="id_price"></p>
    <p><label for="id_available_quantity">Available quantity:</label> <input type="number" name="available_quantity" value="{{item.available_quantity}}" required="" id="id_available_quantity"></p>
    <button type="submit" class="btn btn-dark" style="height:42px;width:140px;" value="{{item.id}}" name="item_id">Edit Item</button>
  </form>
</div>

{% endblock %}

templates/basic_app/walletmoney.html
{% extends "basic_app/homepage.html" %}
{% block dropdown_content %}
<ul class="list-group">
<li class="list-group-item"><a href="#">Username: {{user.username}}<br></a></li>
<li class="list-group-item"><a href="#">Address:  {{customer.Address}}<br></a></li>
<li class="list-group-item"><a href="#">Wallet Balance: {{customer.wallet_balance}}<br></a></li>
<li class="list-group-item"><a href="{% url 'basic_app:customer_home'%}">Home</a></li>
<li class="list-group-item"><a href="{% url 'basic_app:ChangeAddress'%">Change Address</a></li>
<li class="list-group-item"><a href="{% url 'basic_app:AddBalance'%}">Add Money to Wallat</a></li>
<li class="list-group-item"><a href="{% url 'basic_app:Cart'%}">Cart</a></li>
<li class="list-group-item"><a href="{% url 'basic_app:WishList'%}">Wish list</a></li>
<li class="list-group-item"><a href="{% url 'basic_app:CustomerOrderHistory'%}">Order history</a></li>
</ul>

{% endblock %}

{% block base_body %}
<div id="custbox" class="container-fluid">
  <h2>Add balance in wallet</h2>
  <form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    <p><label for="wallet_balance">Add:</label><input type="number" name="wallet_balance" maxlength="100" value="{{customer.wallet_balance}}" required="" id="wallet_balance">
    </p>
    <input type="submit" class="btn btn-dark" name="" value="Add Balance">
  </form>
</div>
{% endblock %}